name: Build and Release Android App

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  BASE_VERSION: '1.0'

jobs:
  android-release-build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Update Version and Set Output
        id: version
        run: |
          MAJOR_MINOR="${{ env.BASE_VERSION }}"
          PATCH="${{ github.run_number }}"
          NEW_SEMANTIC_VERSION="${MAJOR_MINOR}.${PATCH}"
          
          echo "Updating pubspec.yaml version to $NEW_SEMANTIC_VERSION"
          
          sed -i "s/^version: .*/version: $NEW_SEMANTIC_VERSION/" pubspec.yaml
          
          echo "version-number=$NEW_SEMANTIC_VERSION" >> $GITHUB_OUTPUT

      - name: Build APK
        run: |
          flutter build apk --release

      - name: Build App Bundle
        run: |
          flutter build appbundle --release

      - name: Archive APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Archive AAB Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-aab
          path: build/app/outputs/bundle/release/app-release.aab

  create-github-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [ android-release-build ]
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download APK Artifact
        uses: actions/download-artifact@v4
        with:
          name: release-apk

      - name: Download AAB Artifact
        uses: actions/download-artifact@v4
        with:
          name: release-aab

      - name: Get Version Info
        id: version
        run: |
          MAJOR_MINOR="${{ env.BASE_VERSION }}"
          PATCH="${{ github.run_number }}"
          
          FULL_VERSION="${MAJOR_MINOR}.${PATCH}"
          echo "version-number=$FULL_VERSION" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.version.outputs.version-number }}
          name: Release ${{ steps.version.outputs.version-number }}
          draft: false
          prerelease: false
          files: |
            *.apk
            *.aab
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}