name: Build and Release Android App

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  android-release-build:
    name: Android Release Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter (Latest Stable)
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install Dependencies
        run: flutter pub get

      - name: Build APK and App Bundle
        run: |
          flutter build apk --release
          flutter build appbundle --release

      - name: Archive APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Archive AAB Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-aab
          path: build/app/outputs/bundle/release/app-release.aab

  create-github-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [ android-release-build ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: release-apk
      - uses: actions/download-artifact@v4
        with:
          name: release-aab
      - id: version
        uses: NiklasLehnfeld/flutter-version-number-action@v2
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          automatic_release_tag: latest
          title: ${{ steps.version.outputs.version-number }}
          files: |
            *.apk
            *.aab