name: Build and Release Android App

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  android-release-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Increment version
        run: ./increment_version.sh

      - name: Commit updated version file
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.name 'action@github.com'
          # Note: It is safer to pull here to avoid race conditions if multiple builds trigger rapidly,
          # though usually just adding is fine on single concurrent pushes.
          git add version.txt
          git commit -m "Auto-increment build number to $(cat version.txt) [skip ci]"
          git push

      - name: Build APK
        run: flutter build apk --release # or 'build appbundle' for Google Play

      - name: Archive APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Archive AAB Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-aab
          path: build/app/outputs/bundle/release/app-release.aab

  create-github-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [ android-release-build ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: release-apk
      - uses: actions/download-artifact@v4
        with:
          name: release-aab
      - id: version
        uses: NiklasLehnfeld/flutter-version-number-action@v2
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          automatic_release_tag: latest
          title: ${{ steps.version.outputs.version-number }}
          files: |
            *.apk
            *.aab